# Generated by Django 5.2.4 on 2025-11-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agendamiento', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Asistió', 'Asistió'), ('No asistió', 'No asistió')], default='Confirmado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_disciplina', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('cupos_totales', models.IntegerField()),
                ('cupos_disponibles', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
