# Generated by Django 5.2.4 on 2025-11-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_impartidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='sedes.sede'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamientos', to='clases.clase'),
        ),
    ]
