# Generated by Django 5.2.4 on 2025-11-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='estudios.estudio')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['estudio__nombre', 'nombre'],
                'unique_together': {('estudio', 'nombre')},
            },
        ),
    ]
