services:
  backend:
    build: ./backend_django
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend_django:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=pilates_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=PilatesB4ck3nd2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
