# Generated by Django 5.2.4 on 2025-11-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('Enviado', 'Enviado'), ('Recibido', 'Recibido')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Leído', 'Leído'), ('Error', 'Error')], default='Enviado', max_length=10)),
            ],
        ),
    ]
