# Generated by Django 5.2.4 on 2025-11-26 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos_restantes', models.IntegerField(default=0, verbose_name='Créditos Restantes')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crédito de Alumno',
                'verbose_name_plural': 'Créditos de Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa/Studio')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa (Tenant)',
                'verbose_name_plural': 'Empresas (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_creditos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Créditos Incluidos')),
            ],
            options={
                'verbose_name': 'Paquete de Créditos',
                'verbose_name_plural': 'Paquetes de Créditos',
            },
        ),
    ]
