# Generated by Django 5.2.4 on 2025-11-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos_otorgados_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Alumno Propietario'),
        ),
        migrations.AddField(
            model_name='creditoalumno',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sedes.sede', verbose_name='Sede donde se compró'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='empresas.empresa', verbose_name='Disponible para Empresa'),
        ),
        migrations.AddField(
            model_name='creditoalumno',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.paquete', verbose_name='Paquete Adquirido'),
        ),
    ]
