# Generated by Django 5.2.4 on 2026-03-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('Exitoso', 'Exitoso'), ('Fallido', 'Fallido')], max_length=10)),
            ],
        ),
    ]
