# Generated by Django 5.2.4 on 2025-11-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('Exitoso', 'Exitoso'), ('Fallido', 'Fallido')], max_length=10)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='sedes.sede')),
            ],
        ),
    ]
