# Generated by Django 5.2.4 on 2026-03-27 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='sedes.sede'),
        ),
    ]
