# Generated by Django 5.2.4 on 2025-11-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referido', models.CharField(max_length=50, unique=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('recompensa_otorgada', models.BooleanField(default=False)),
            ],
        ),
    ]
