# Generated by Django 5.2.4 on 2025-11-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referido',
            name='referido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referidos_usados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referido',
            name='referidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
