# Generated by Django 5.2.4 on 2025-11-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo para personalización de marca', max_length=300, null=True)),
                ('contacto_email', models.EmailField(blank=True, help_text='Email de contacto administrativo', max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['nombre'],
            },
        ),
    ]
